# -*- coding: utf-8 -*-
"""aula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PYzmbEHqHqG86Rk9L3K6qZfxlu_pioex

AULA 3 - ANÁLISE EXPLORATÓRIA
"""

#IMPORTANDO AS BIBLIOTECAS

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

#ABRINDO O ARQUIVO DA BASE

from google.colab import files
arq = files.upload()

#CRIANDO O DATA FRAME

df = pd.read_excel("AdventureWorks.xlsx")

df.head()

df.shape #Tamanho do arquivo

df.dtypes #Visualizando os tipos de cada coluna

#Receita Total

df["Valor Venda"].sum()

#Custo Total - criando nova coluna do custo total

df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"])

df.head(5)

#Qual o custo total?

df["Custo"].sum()

#Lucro

df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(5)

round(df["Lucro"].sum(),2) #arrendando em 2 casas decimais

#Tempo de que levou as entregas

df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(5)

#Mèdia de tempo de envio por marca

df.groupby("Marca")["Tempo_envio"].mean()

#Verificar se tem valores em branco

df.isnull().sum()

#Agrupar por ano e marca para saber por ano quanto cada marca vende

df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

#formatando para uma melhor visualização

pd.options.display.float_format = '{:20,.2f}'.format

lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()
lucro_ano

#Total de Produtos vendidos

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

"""GRÁFICOS"""

#Produtos vendidos em gráfico

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

#Lucro por Ano

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df_2009 = df[df["Data Venda"].dt.year == 2009]
df_2009.head(5)

#Lucro mensal de 2009

df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucro");

#Lucro por marca

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal"); #rotaciona o eixo

#Lucro por classe

df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title="Lucro x Classe")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal"); #rotaciona o eixo

#Analises Estatísticas

df["Tempo_envio"].describe()

#Grafico Boxplot

plt.boxplot(df["Tempo_envio"]);

#Grafico Histograma

plt.hist(df["Tempo_envio"]);

#Identificando o Outlier

df[df["Tempo_envio"] == 20]

