# -*- coding: utf-8 -*-
"""aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGBOSeJgvjQZ_UhbfodrgK16zg5t1-qN

AULA 1
"""

#importando biblioteca

import pandas as pd

#Criando o DataFrame

df = pd.read_csv("Gapminder.csv",error_bad_lines=False,sep=";")

#Renomeando as colunas

df = df.rename(columns={"country": "País", "continent": "Continente", "year": "Ano", "lifeExp": "Expect. de Vida", "pop": "População", "gdpPercap": "PIB"})

print(df.head(10)) #imprime primeiras linhas

print(df.shape)    #tamanho do arquivo

print(df.columns)  #cabeçalho colunas

print(df.dtypes)   #tipo de cada colunas

print(df.tail())   #imprime ultimas linhas

print(df.describe()) #resumo das informações, máx, min, desvio...

print(df["Continente"].unique()) #tranzendo todos os dados unicos da coluna continente

#Extraindo todos os dados apenas do continente ociania e colocando em uma váriavel

oceania = df.loc[df["Continente"] == "Oceania"]
print(oceania.head())

#Agrupando dados por uma coluna, quantos paises tem nos continentes
print(df.groupby("Continente")["País"].nunique())
print("")

#mean = média / para cada ano qual era a expectativa de vida

print(df.groupby("Ano")["Expect. de Vida"].mean())
print("")

#média e soma do PIB

print(df["PIB"].mean())
print(df["PIB"].sum())

